### ISSUE TITLE
A weird filename in the releases page

### ISSUE THREAD

**Issue by remore** [haconiwa/haconiwa#133]
Not sure if it's intended or not, but I happened to find that release binary filename for v0.8.9 doesn't follow the naming convention.

Specifically, in the [releases](https://github.com/haconiwa/haconiwa/releases) page, there is the file `haconiwa-v0.8.8.x86_64-pc-linux-gnu.tgz` but it's listed under the v0.8.9 release.

**Comment by udzura** [comment]
You mean, the file name on v0.8.9 release looks wrong?

Anyway I'm going to rebuild and re-upload this. Thanks.

**Comment by remore** [comment]
Ah, I just wanted to say that the version number looks inconsistent.
![image](https://user-images.githubusercontent.com/424277/35326780-0ff368aa-013b-11e8-959d-84f571682885.png)

**Comment by remore** [comment]
Just to be clear and FYI, I found this because I have tried following installation steps guided in the README.md:
```
VERSION=0.8.0
wget https://github.com/haconiwa/haconiwa/releases/download/v${VERSION}/haconiwa-v${VERSION}.x86_64-pc-linux-gnu.tgz
```

I have used `VERSION=0.8.9` for my installation but that failed with the status code 404.

**Comment by udzura** [comment]
お互い英語なので通じ合っていない！！１
最新がバージョン0.8.9であることは正しく（packagecloudなどもそうなっていると思います。間違っていたら教えてください...）、READMEの手順も正です。
一方、github.comの0.8.9リリースを作る時に手順を間違えたと思うので、そこはビルドし直しの上で修正します。ご指摘ありがとうございます。

**Comment by remore** [comment]
> 最新がバージョン0.8.9であることは正しく（packagecloudなどもそうなっていると思います。間違っていたら教えてください...）、READMEの手順も正です。
はい、0.8.9が最新で、かつREADMEの手順も正だと認識しております。
英語で分かりづらくしてしまっていたらごめんなさい。ファイル名が0.8.8になってたのでwgetでコケました、という報告をしたかったのみです :pray:

**Comment by udzura** [comment]
PRと違ってパッチがなく言葉だけなので難しかったですね。すぐ時間が取れないのですがともかくファイルは上げ直す予定です。

I think issues are less clear than PRs because they are without patches :)

**Comment by udzura** [comment]
📝  BTW `a` is used before `weird` generally... as used in `a world` or `a wine barrel`
[ref](https://www.a-or-an.com/a_an/weird)

**Comment by remore** [comment]
Ohhh didn't know [that](https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1172112996). Thank you for the bonus advice too!

**Comment by remore** [comment]
Not a problem at all~

**Comment by udzura** [comment]
Re-uploaded. thanks!
https://github.com/haconiwa/haconiwa/releases/tag/v0.8.9
